package excaptionHandlingPackage;

public class NestedTryExample {

	public static void main(String[] args) {

		try {
			try {
				System.out.println("Inside nested try block");
				int a = 300 / 0;
			} catch (ArrayIndexOutOfBoundsException e) {
				System.out.println(e);
			} finally {
				System.out.println("Will get excecuted");
			}
			try {
				int b[] = { 13, 15, 17, 19, 21, 23, 24 };
				System.out.println(b[12]);
			} catch (Exception e) {
				System.out.println(e);
			}
			System.out.println("Continue");
		} catch (Exception e) {
			System.out.println(e);
		}
		System.out.println("Rest of the code...");

	}

}
